apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoia3VuOTkiLCJwYXNzd29yZCI6ImdocF9FcHU5QUw5REU5Wk1jSUc5UGtHZG5kWmJ4d3Z1QlgxUWRheUkiLCJhdXRoIjoiYTNWdU9UazZaMmh3WDBWd2RUbEJURGxFUlRsYVRXTkpSemxRYTBka2JtUmFZbmgzZG5WQ1dERlJaR0Y1U1E9PSJ9fX0=
kind: Secret
metadata:
  name: p2secret
type: kubernetes.io/dockerconfigjson
